[package]
name = "link_rust"
version = "0.1.0"
edition = "2021"


[dependencies]
actix-web = "4"
tokio = {version = "1", features = ["macros", "rt-multi-thread"]}
reqwest = {version = "0.11", features = ["blocking"]}
serde = {version = "1.0", features = ["derive"]}
scraper = "0.14.0"