[package]
name = "link_rust"
version = "0.1.0"
edition = "2021"


[dependencies]
actix-web = "4"
tokio = {version = "1", features = ["macros", "rt-multi-thread"]}
reqwest = "0.11"
select = "0.5.0"
serde = {version = "1.0", features = ["derive"]}